---
locale: en
tags: []
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: true
choices: []
name: The water got cold
