---
locale: en
tags: []
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: Last one out, turn off the lights
