---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`volume` is a local variable"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`volume` is a global variable"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`turn_volume_up` is a function"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`turn_volume_up` is a procedure"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`turn_volume_down` is a function"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`turn_volume_down` is a procedure"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`is_safe_volume` is a function"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`is_safe_volume` is a procedure"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`turn_volume_up` returns a number"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`is_safe_volume` returns a number"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`is_safe_volume` returns a boolean"
  checked: true
name: Bajemos el volumen
